version: "3.8"
services:

  postgres_db:
    image:  postgres-cust
    build: ./images/postgresql/
    container_name: postgres-db
    restart: unless-stopped
    environment: &postgres_auth
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=events
    ports:
      - "5432:5432"
    volumes:
      - postgres_db:/var/lib/postgresql/data
      - data:/data

  python:
    image: python:3.7.10-slim
    build: ./images/base_python_image/
    container_name: pythonc
    command: sleep 400
    environment:
      - RAW_DATA_PATH=/project/raw_data
    volumes:
      - data:/data





volumes:
  postgres_db:
  data:
