version: "3.8"

services:

  postgres_db:
    image:  postgres-cust
    build: ./images/postgresql/
    container_name: postgres-db
    restart: unless-stopped
    environment: &postgres-auth
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: password
      POSTGRES_DB: events
    ports:
      - "5432:5432"
    volumes:
      - data:/tmp

  python:
    image: python:3.7.10-slim
    build: ./images/base_python_image/
    depends_on:
      - postgres_db
      - tests
    tty: true # keeps container running in interactive mode
    container_name: python-app
    environment:
      <<: *postgres-auth
      POSTGRES_HOST: postgres-db
      POSTGRES_PORT: 5432
      PYTHONPATH: /project/scripts
    volumes:
      - data:/tmp


volumes:
  data:
